# Generated by Django 4.2.5 on 2023-10-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_userlocation_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="custom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=20)),
                ("birthday", models.DateField()),
                ("occupation", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=False)),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("additional_data", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UserLocation",
        ),
    ]
