# Generated by Django 4.2.5 on 2023-10-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_sell"),
    ]

    operations = [
        migrations.CreateModel(
            name="admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
    ]
