# Generated by Django 4.2.5 on 2023-11-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="image_upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
            ],
        ),
    ]
