# Generated by Django 4.2.5 on 2023-11-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_image_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image_upload",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
