# Generated by Django 4.2.5 on 2023-11-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_image_upload_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image_upload",
            name="image",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
